### ISSUE TITLE
consulta sobre regla 2

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#11]
Al parsear esa cadena:
>  "{int y=3;}"

Este es el resultado

> Error 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 8
Error 17: existen llaves superfluas. Line: 0, Column: 0

1. Me parece que no debemos incluir la palabra `Error` en el linter, tener llaves superfluas no es un error de codigo, me gusta mas la palabra `Warning` , `Cuidado`, `Atencion`
2. Esta bien que el linter indique que No debe haber mas de un statement en la misma linea

**Comment by mconiglio** [comment]
Resolved to show "Offense detected" instead from "Error" 9809aa5
