### ISSUE TITLE
Regla #2, caso 3: "{int y=2;\n\n\ny=3;}");

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#14]
No Se esperaba recibir "No debe haber mas de un statement en la misma linea." pero el resultado fue 
Offense detected - 1: existe mas de un salto de linea consecutivo. Line: 0, Column: 9
Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 3, Column: 3 evaluando:
{int y=2;

y=3;}

**Comment by mconiglio** [comment]
La ofensa 1 esta bien que aparezca porque hay dos lineas en blanco consecutivas. Eso responde tu pregunta?

**Comment by nandotorterolo** [comment]
Gracias.

[info] The '{y=2;
[info] y=3;}' string should
[info] + not contain message Offense detected - 1: existe mas de un salto de linea consecutivo.
[info] 
[info] The '{y=2;
[info] 
[info] y=3;}' string should
[info] + not contain message Offense detected - 1: existe mas de un salto de linea consecutivo.
[info] 
[info] The '{y=2;
[info] 
[info] 
[info] y=3;}' string should
[info] + contain message Offense detected - 1: existe mas de un salto de linea consecutivo.
[info] 
[info] The '{y=2;
[info] 
[info] 
[info] 
[info] y=3;}' string should
[info] + contain message Offense detected - 1: existe mas de un salto de linea consecutivo.
[info] 
[info] Total for specification rule1
[info] Finished in 14 ms
[info] 4 examples, 0 failure, 0 error
