### ISSUE TITLE
FunctionDeclaration, toString, 

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#15]
@juanpale @mconiglio 
El metodo toString, en FunctionDeclaration, esta mal implementada.

Si se intenta parser con alguno de estos valores,
`protected void loadData() {
        datosPruebas.put(1, "function bool negacion(bool a, bool False) return !a;");
        datosPruebas.put(2, "function bool negacion() return !a;");
    }`

arroja el siguiente error:
`java.lang.ClassCastException: java.util.LinkedHashMap$LinkedValues cannot be cast to java.util.List`

Esta implementacion esta MAL

> 	@Override public String toString() {
> 		String devolver="function "+type+" "+id+" (";
> 		List <String>keys=(List) parameters.values();
> 		int i=0;
> 		for (String parameter:keys){
> 			devolver+=parameter+" "+parameters.get(parameter);
> 			i++;
> 			if (i!=keys.size()){
> 				devolver+=",";
> 			}
> 		}
> 		devolver+=");";
> 		return devolver;
> 	}
> 

	Sustituir por esta implementacion donde no se castea a un lista.

> @Override public String toString() {
> 		String devolver = "function " + type + " " + id + " (";
> 		for (String parameter:parameters.values()){
> 			 devolver += parameter + " " +  parameters.get(parameter) + ", ";
> 		}
> 		// en caso de haber parametros, le quito los 2 ultimos caracteres ", "
> 		if(!parameters.isEmpty()) devolver = devolver.substring(0,devolver.length() -2);
> 		return devolver + ");";
> 	}
>

**Comment by mconiglio** [comment]
Resolved 8fadf39
