### ISSUE TITLE
Regla 3, errores

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#16]
Luego de arreglar el issue, sobre el toString, #15 
 Probar alguno de estos 3 ejemplos, y ver porque se rompe en el log de abajo.
 
```
protected void loadData() {
        datosPruebas.put(1, "function bool negacion(bool a, bool b) {bool c=a&&b; return c;}");
        datosPruebas.put(2, "{function bool negacion() {return !a;}}");
        datosPruebas.put(3, "function int entero(int a) return a;");
    }
```

```
INFO: function Boolean negacion (Boolean null, Boolean null);
java.lang.NullPointerException
	at ucu.ast.Return.checkLinter(Return.java:52)
	at ucu.ast.Sequence.checkLinter(Sequence.java:67)
	at ucu.ast.FunctionDeclaration.checkLinter(FunctionDeclaration.java:82)
	at ucu.TestRule3.testData1(TestRule3.java:40)

```	

El problema esta en la clase Return, dentro del if, se hace un s.mapa.get, pero no se controla el caso de que el mapa no contenga la key que se le pasa.
Por otro lado, no entiendo cual es el objetivo de tener en Stme este nombre de funcion.
`public String idFunction="";`

> public CheckStateLinter checkLinter(CheckStateLinter s) {
> 		if (exp.countOperators() > 7) CheckStateLinter.addError20(exp.countOperators(), line, column);
> 		
> 		String tipoExp=exp.checkLinter(s);		
> 		if (s.mapa.get(this.idFunction).tipo.equals("Void")){
> 			CheckStateLinter.addError12A(this.idFunction, line, column);
> 		}
> 		else if (tipoExp.equals(s.mapa.get(this.idFunction).tipo)){
> 			CheckStateLinter.addError12B(this.idFunction, line, column);
> 		}
> 		ArrayList <String> tiposAceptados=new ArrayList<String>();
> 		tiposAceptados.add(s.mapa.get(this.idFunction).tipo);
> 		CheckStateLinter.evaluarRegla9(this.exp, s, tiposAceptados);
> 		///ver que hago con idFunction de stmt
> 		return s;
> 	}
>

**Comment by mconiglio** [comment]
Solved
