### ISSUE TITLE
En clase Stmt, no es necesario boxear, return ((Double) obj).doubleValue();

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#17]
> public static double toDouble(Object obj,String unparse) {
> 		if (obj instanceof Integer){
> 			return ((Integer) obj).doubleValue();
> 		}else if (obj instanceof Double){
> 			return ((Double) obj).doubleValue();
> 		}else{
> 			throw new IllegalStateException(unparse);
> 		}
> 	}

Sustituir por ese metodo

> public static double toDouble(Object obj,String unparse) {
> 		if (obj instanceof Integer){
> 			return ((Integer) obj).doubleValue();
> 		}else if (obj instanceof Double){
> 			return (Double) obj;
> 		}else{
> 			throw new IllegalStateException(unparse);
> 		}
> 	}

**Comment by mconiglio** [comment]
Solved 3c29fa2
