### ISSUE TITLE
Regla número 4:  Detectar variables declaradas sin usar;

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#18]
`String strParse = "{int a; int b; int c; a=1; b=a;}"; `

Esta cadena parsea correctamente:
INFO: Sequence([AssignmentStmtWithType(a, null), AssignmentStmtWithType(b, null), AssignmentStmtWithType(c, null), Assignment(a, Numeral(1)), Assignment(b, Variable(a))])

Pero al correr el linter, tira una error.
java.lang.NullPointerException
	at ucu.ast.AssignmentStmtWithType.checkLinter(AssignmentStmtWithType.java:131)

Hay que modificar el parser para que no reciba null en estos caso, hay 3 reglas en el parser, que cuando se generan se crean con un valor null.

1.  // stmtFunctions ::= tipo ID SEMICOLON 
 RESULT = new AssignmentStmtWithType($5, $1,**null**,$5left, $5right); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmtFunctions",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }

2.   // stmtMain ::= tipo ID SEMICOLON 
 RESULT = new AssignmentStmtWithType($5, $1,**null**,$5left, $5right); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmtFunctions",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }

3.  // stmtBasics ::= tipo ID SEMICOLON 
RESULT = new AssignmentStmtWithType($5, $1,**null**,$5left, $5right); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmtBasics",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }

**Comment by nandotorterolo** [comment]
en el caso de que no se pueda declarar variables sin incializar:

`String strParse = "{int a=1; int b=2; int c=3; a=1; b=a;}";`

Parsea correctamente

INFO: Sequence([AssignmentStmtWithType(a, Numeral(1)), AssignmentStmtWithType(b, Numeral(2)), AssignmentStmtWithType(c, Numeral(3)), Assignment(a, Numeral(1)), Assignment(b, Variable(a))])

Pero no detecta la regla, 
Detectar variables declaradas sin usar;

Este es el resultado del linter.

> Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 17
> Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 26
> Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 31
> Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 36

**Comment by mconiglio** [comment]
Running this:
`{int a=1; int b=2; int c=3; a=1; b=a;}`

you get this:

```
Offense detected - 4: variable definida sin usar. Line: 0, Column: 19
Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 10
Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 19
Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 28
Offense detected - 2: No debe haber mas de un statement en la misma linea. Line: 0, Column: 33
```
