### ISSUE TITLE
Regla numero 6, cambiar a Mayuscula la "L" en mensaje

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#19]
El mensaje es el siguiente,

> Offense detected - 6: `las` variables deben comenzar con minuscula y sin guiones bajos. 

cambiar por

> Offense detected - 6: `Las` variables deben comenzar con minuscula y sin guiones bajos.

**Comment by nandotorterolo** [comment]
Mismo comentario para todos los mensajes de error, para ver que cambiar, mirar la paabra `sombreada`, también tengo problemas de encoding con todos los tildes, traten de que el ide, quede configurado en UTF-8. 
Los test, verrifican el comportamiento, si a la vuelta del linter, los mensajes de errrores contiene el mensaje esperado, por eso es problematico el tema de tilde, o sensitividad de las letras.

> public static void addError1(int line, int column) {
>       addError("1", "`existe` mas de un salto de linea consecutivo", line, column); 
>   }
> 
>   public static void addError2(int line, int column) {
>       addError("2", "No debe haber mas de un statement en la misma linea", line, column);
>   }
> 
>   public static void addError3(int line, int column) {
>       addError("3", "`funcion` declarada sin llamar", line, column); 
>   }
> 
>   public static void addError4_11(int line, int column) {
>       addError("4-11", "`variable` definida sin usar", line, column); 
>   }
> 
>   public static void addError5A(int line, int column) {
>       addError("5A", "La `condici�n` no es necesaria", line, column);
>   }
> 
>   public static void addError5B(int line, int column) {
>       addError("5B", "El codigo interno no se `ejecutar�`nunca", line, column);
>   }
> 
>   public static void addError5C(int line, int column) {
>       addError("5C", "El codigo del else no `ejecutar�`nunca", line, column);
>   }
> 
>   public static void addError5D(int line, int column) {
>       addError("5D", "El `codigo` del then no `ejecutar�` nunca", line, column);
>   }
> 
>   public static void addError6(int line, int column) {
>       addError("6", "`las` variables deben comenzar con minuscula y sin guiones bajos", line, column); 
>   }
> 
>   public static void addError7(int line, int column) {
>       addError("7", "`los` nombres de metodos deben comenzar con minuscula", line, column); 
>   }
> 
>   public static void addError8(String variableId, int line, int column) {
>       addError("8", "`variable` " + variableId + " no declarada", line, column);
>   }
> 
>   public static void addError10A(int line, int column) {
>       addError("10A", "`cantidad` de parametros de funcion incorrectos", line, column);
>   }
> 
>   public static void addError10B(String expectedType, String parameterType, int line, int column) {
>       addError("10B", "`parametro` de funcion de tipo incorrecto. Esperado: " + expectedType + ", actual: " + parameterType, line, column);
>   }
> 
>   public static void addError12A(String functionName, int line, int column) {
>       addError("12A", "`la` funcion " + functionName + " no devuelve nada segun su definicion", line, column); 
>   }
> 
>   public static void addError12B(String functionName, int line, int column) {
>       addError("12B", "El tipo de la expresion del return no coincide con el la `funci�n` " + functionName, line, column); 
>   }
> 
>   public static void addError13(String functionName, int line, int column) {
>       addError("13", "`la` funcion " + functionName + " ya se encuentra definida", line, column); 
>   }
> 
>   public static void addError14_19(String variableId, int line, int column) {
>       addError("14-19", "`la` variable " + variableId + " ya se encuentra declarada", line, column);
>   }
> 
>   public static void addError16(int line, int column) {
>       addError("16", "`existen` parentesis superfluos", line, column);
>   }
> 
>   public static void addError17(int line, int column) {
>       addError("17", "`existen` llaves superfluas", line, column);
>   }
> 
>   public static void addError18A(String functionName, String oldFunctionName, int line, int column) {
>       addError("18A",  "`la` funcion " + functionName + " se encuentra definida como " + oldFunctionName, line, column);
>   }
> 
>   public static void addError18B(String variableId, String oldVariableId, int line, int column) {
>       addError("18B", "`la` variable " + variableId + " se encuentra definida como " + oldVariableId, line, column);
>   }
> 
>   public static void addError20(int operators, int line, int column) {
>       addError("20", "`existe` una expresion con " + operators + " operadores", line, column);
>   }
> 
>   public static void addError21(int nestingLevels, int line, int column) {
>        addError("21", "`existe` un statement con " + nestingLevels + " niveles de anidacion", line, column);
>   }

**Comment by mconiglio** [comment]
Solved 1973c35
