### ISSUE TITLE
Regla 6. Los nombres de la variables deben comenzar con minúsculas y sin guiones bajos

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#20]
> String strParse = "function int myfuncion(int _a, int A){skip;}";

Esta secuencia parsea a: 

> INFO: Sequence([AssignmentStmtWithType(a, Numeral(1)), AssignmentStmtWithType(_ad, Numeral(2))])

Deberia tirrar un error 6, pues la variables definidad como parametros de funcion, no respetan la regla?

**Comment by mconiglio** [comment]
Solved 1973c35
