### ISSUE TITLE
Regla 7:  Los nombres de los métodos deben comenzar con minúsculas

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#21]
unction int _mi_Funcion(int _a, int A){skip;}

Se debe chequear guiones bajos al comienzo, en nombre de funciones, al igual que nombres de variables?

**Comment by mconiglio** [comment]
No, en las funciones solo se debe chequear que su nombre comience con minúscula. No importa si comienzan con `_`
