### ISSUE TITLE
Cadenas que parsean, pero rompen el linter., NO borrar este hilo

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#22]
> {int a=1; int b=2; bool d=True; function bool fun1(int a, int b) {return d;}}

> Parse: INFO: Sequence([AssignmentStmtWithType(a, Numeral(1)), AssignmentStmtWithType(b, Numeral(2)), AssignmentStmtWithType(d, Variable(True)), 
function Boolean fun1 (Integer null, Integer null);])

> Lint: java.lang.NullPointerException, 	at ucu.ast.Return.checkLinter(Return.java:52)

**Comment by nandotorterolo** [comment]
cadena

> function bool negacion(bool a, bool b) {bool c=a&&b; return c;}

parser

> INFO: function Boolean negacion (Boolean null, Boolean null);

linter

> java.lang.NullPointerException
>     at ucu.ast.Return.checkLinter(Return.java:52)

**Comment by nandotorterolo** [comment]
cadena

> {function bool negacion() {return !a;}

parser

> INFO: Sequence([function Boolean negacion ();])

linter

> java.lang.NullPointerException    at ucu.ast.Return.checkLinter(Return.java:52)

**Comment by nandotorterolo** [comment]
cadena

> function int entero(int a) return a;

parser

> INFO: function Integer entero (Integer null);

linter

> java.lang.NullPointerException , at ucu.ast.Return.checkLinter(Return.java:52)

**Comment by mconiglio** [comment]
Todos esos casos han sido resueltos.
