### ISSUE TITLE
stmtMain, 

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#23]
No entiendo esta regla en el parser, 

> |	FUNCTION:$5 tipoFuncionesDef:$1 ID:$4 LEFT_PARENTHESIS parametrosConTipo:$2 RIGHT_PARENTHESIS stmtFunctions:$3
		{: RESULT = new FunctionDeclaration($4, $1, $2, $3, $5left, $5right); :}

Creo que la regla deberia ser de esta forma, omiti los identificadores $.

> |	FUNCTION tipoFuncionesDef ID LEFT_PARENTHESIS parametrosConTipo RIGHT_PARENTHESIS LEFT_CURLY_BRACKET repeatstmtFunctions RIGHT_CURLY_BRACKET

De esta forma el cuerpo de las funciones, queda bien definido, 

Ejemplo: Acutualmente, este string parsea:
> {function int entero(int a) a=b;}
Pero no me queda claro que hace.

**Comment by juan-lemos** [comment]
Fernando estas equivocado.
Debido a que te estas olvidando que todo stmt puede potencialmente ser una secuencia de stmt y esta última tiene {}
Por otra parte consideramos ese string que pusiste válido.

**Comment by nandotorterolo** [comment]
Si es un string valido 
`{function int entero(int a) a=b;}`
no entiendo que es lo que hace, necesito ayuda.
podes darme un ejemplo de un un sequencia de statments que hagan los siguientos.
Quiero hacer este test, y ver el comportamiento del linter,  con esta secuencia. Pero no se como hacerlo. Con lo que hay desarrollado hasta ahora, se puede hacer? Por lo que vi del parser, se puede definir funciones sin cuerpo. Quizas lo entendi mal.
1. defina una funcion que retorno int, nombre identidad, de 1 parametro int, sin cuerpo
2. defina una fucnion que retorno int, nombre duplica, de 1 parametro int, con cuerpo implementado
3. crear una variable entera x asignada a 1
4. crar una variable entera y asinganda a la funcion   y=duplica(x); , como tiene cuerpo puedo llamarla
5. definar el cuerpo de la funcion definida arriba. identidad
6. crear una variable entera usando   z=identidad(x+y) + duplica(x) + duplica(y)

**Comment by mconiglio** [comment]
Fernando:
1. No aceptamos funciones sin cuerpo.
2. `function int duplica(int n) return 2*n;`
3. `int x = 1;`
4. `int y = duplica(x);`
5. No se permite redefinir cuerpos de funciones.
6. `int z = duplica(x) + duplica(y);`
