### ISSUE TITLE
Regla 16 - No existan parentesis superfluos

### ISSUE THREAD

**Issue by CynDD** [juanpale/ObligatorioWhile#25]
Con el caso de prueba {int y=3;int x=32 ;int z= ((15<=10)) ? 15<=10 : ((15==10));} me detecta solo en un lugar que hay parentesis superfluos. El test devuelve: Offense detected - 16: Existen parentesis superfluos. Line: 0, Column: 48

**Comment by mconiglio** [comment]
Resuelta la detección de paréntesis superfluos en la condición. cf24859

Pendiente: guardar el numero de linea y columna de las expresiones para después mostrarlo en la ofensa detectada.
