### ISSUE TITLE
Offense detected - 11: Parametro sin usar. Line: 1, Column: 1

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#28]
En este caso, tengo 4 parametros sin usar,  

> int a, bool b, num c, str d

Se puede agregar el nombre de la variable que no estoy usando.
Ademas de eso, porque todos los mensajes me dan igual, entiendo que la fila esta bien, pero la columna debe variar.

>  Line: 1, Column: 1

```
[info] rule11
[info] 
[info] The case2: '{
[info]  function int identidad(int a, bool b, num c, str d) {
[info]    return 1;
[info]  }
[info] 
[info]  int b = identidad(a);
[info]  bool c = identidad(a);
[info]  print(b);
[info] }' string should
[info] + contain messages:
[info]   Offense detected - 11: Parametro sin usar. Line: 1, Column: 1
[info]   Offense detected - 11: Parametro sin usar. Line: 1, Column: 1
[info]   Offense detected - 11: Parametro sin usar. Line: 1, Column: 1
[info]   Offense detected - 11: Parametro sin usar. Line: 1, Column: 1

```

**Comment by juan-lemos** [comment]
el problema se informa a nivel línea de definición de función
Para hacer eso habría que agregar nuevos nodos de ast que sea parámetros y modificar el parser
