### ISSUE TITLE
Regla 18 - No escribir nombres de variables o métodos iguales pero que se diferencien en solamente en mayúsculas y minúsculas Ej: ''numeric a=23; numeric A=23''

### ISSUE THREAD

**Issue by CynDD** [juanpale/ObligatorioWhile#29]
Con nombres de metodos no esta devolviendo que son iguales. Caso de ejemplo: Hola(y,x); hOLA(y,x);

**Comment by juan-lemos** [comment]
Este caso se detecta, pero no a nivel de llamadas sino que nivel de definiciones
{function Void Hola(int x){} function Void hola(int x){}}
