### ISSUE TITLE
Clase no definida en AST: FunctionDeclaration

### ISSUE THREAD

**Issue by nandotorterolo** [juanpale/ObligatorioWhile#4]
{: RESULT = new FunctionDeclaration($4, $1, $2, $3); :}
https://github.com/juanpale/ObligatorioWhile/blob/c7dec379737a6cb31b76e7255dba2580ad7dc2de/while_ut1Obligatorio/src/examples/while_ut1/Parser.cup#L110

**Comment by mconiglio** [comment]
Resolved efbdb7f
